import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import json
import os
from pathlib import Path

# Import functional library (Ensure A_Final_feature_extract.py is in the same directory)
import A_Final_feature_extract as fe

# ==========================================
# 1. Configuration and Paths
# ==========================================
# Input: First-level coarse-grained results
INPUT_JSONL = "detail.jsonl"
# Feature file path (extracted and generated by videotrans.py)
FEAT_FILE_PATH = "1226_feat.npy"
# Output: Second-level fine-grained results
OUTPUT_JSONL = "final_test_data\1226spin2.jsonl"

MODEL_WEIGHTS = "best_model.pth"
BUFFER_SECONDS = -4.0  # Corresponding to the pre/post buffer in the previous merged format

# Action Mapping
ACTION_MAP = {
    "Background": 0, "UF": 1, "US": 2, "UB": 3, "SF": 5, "SS": 6, "SB": 7,
    "CF": 8, "CS": 9, "CU": 10, "Willmind": 11, "Other-NBP": 12, "BU": 13, "BS": 14, "BC": 15,
    "Jump In": 16, "Step In": 17, "Difficult In": 18, "Jump Out": 19, "Step Out": 20, "Difficult Out": 21,
    "Trans": 22, "CP": 23, "JCP": 24, "UF+Inside": 25, "SF+Inside": 26, "CF+Inside": 27,
    "CS+Inside": 28, "CU+Inside": 29, "BC+Inside": 30, "SB+Inside": 31,
    "UL+Side": 32, "UL+Up": 33, "UL+Knife": 34,
}
INV_MAP = {v: k for k, v in ACTION_MAP.items()}


# ==========================================
# 2. Model Definition
# ==========================================
class PredictionGeneration(nn.Module):
    def __init__(self, num_layers, num_f_maps, dim, num_classes):
        super(PredictionGeneration, self).__init__()
        self.conv_1x1 = nn.Conv1d(dim, num_f_maps, 1)
        self.layers = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(num_f_maps, num_f_maps, 3, padding=2 ** i, dilation=2 ** i),
                nn.ReLU(),
                nn.Conv1d(num_f_maps, num_f_maps, 1),
                nn.Dropout(0.3)
            ) for i in range(num_layers)
        ])
        self.conv_out = nn.Conv1d(num_f_maps, num_classes, 1)

    def forward(self, x):
        out = self.conv_1x1(x)
        for layer in self.layers: out = out + layer(out)
        return self.conv_out(out)


class MultiStageModel(nn.Module):
    def __init__(self, num_stages, num_layers, num_f_maps, dim, num_classes):
        super(MultiStageModel, self).__init__()
        self.stage1 = PredictionGeneration(num_layers, num_f_maps, dim, num_classes)
        self.stages = nn.ModuleList([
            PredictionGeneration(num_layers, num_f_maps, num_classes, num_classes)
            for _ in range(num_stages - 1)
        ])

    def forward(self, x):
        outputs = []
        out = self.stage1(x)
        outputs.append(out)
        for stage in self.stages:
            out = stage(torch.softmax(out, dim=1))
            outputs.append(out)
        return outputs


# ==========================================
# 3. Processing Logic
# ==========================================
def get_segments(preds, start_time):
    """Convert the sequence of predicted frames into timed segments"""
    if len(preds) == 0: return []

    segments = []
    curr_label_idx = preds[0]
    curr_start_idx = 0

    for i in range(1, len(preds)):
        if preds[i] != curr_label_idx:
            # Convert time: (index * stride) / FPS + spin start time
            begin_t = (curr_start_idx * fe.STRIDE) / fe.FPS + start_time
            end_t = (i * fe.STRIDE) / fe.FPS + start_time

            segments.append({
                "label": INV_MAP.get(curr_label_idx, "Background"),
                "begin": round(begin_t, 3),
                "end": round(end_t, 3)
            })
            curr_label_idx = preds[i]
            curr_start_idx = i

    # Last segment
    begin_t = (curr_start_idx * fe.STRIDE) / fe.FPS + start_time
    end_t = (len(preds) * fe.STRIDE) / fe.FPS + start_time
    segments.append({
        "label": INV_MAP.get(curr_label_idx, "Background"),
        "begin": round(begin_t, 3),
        "end": round(end_t, 3)
    })

    # Filter out Background and ultra-short segments (optional)
    return [s for s in segments if s["label"] != "Background"]


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # 1. Load data and features
    print(f"[*] Reading first-level intervals: {INPUT_JSONL}")
    with open(INPUT_JSONL, 'r', encoding='utf-8') as f:
        first_stage_data = [json.loads(line) for line in f]

    print(f"[*] Loading feature file: {FEAT_FILE_PATH}")
    full_feats = np.load(FEAT_FILE_PATH)

    # 2. Load model
    model = MultiStageModel(num_stages=4, num_layers=10, num_f_maps=64, dim=768, num_classes=36).to(device)
    model.load_state_dict(torch.load(MODEL_WEIGHTS, map_location=device, weights_only=True))
    model.eval()

    results = []

    # 3. Refine each coarse-grained interval
    for item in first_stage_data:
        spin_id = item['spin_id']
        t_start, t_end = item['start'], item['end']

        # Calculate feature indices (Time -> Frame -> Feature Index)
        idx_start = int((t_start * fe.FPS) / fe.STRIDE)
        idx_end = int((t_end * fe.FPS) / fe.STRIDE)

        # Slice features
        feat_part = full_feats[idx_start:idx_end]
        if len(feat_part) == 0: continue

        feat_tensor = torch.from_numpy(feat_part).float().unsqueeze(0).transpose(1, 2).to(device)

        with torch.no_grad():
            outputs = model(feat_tensor)
            preds = torch.argmax(outputs[-1], dim=1).squeeze(0).cpu().numpy()

        # Parse pose segments
        segments = get_segments(preds, t_start)

        # Construct merged format
        merged_entry = {
            "spin_id": spin_id,
            "start": t_start,
            "end": t_end,
            "segments": segments,
            "clip_start": round(max(0, t_start - BUFFER_SECONDS), 3),
            "clip_end": round(t_end + BUFFER_SECONDS, 3),
            "video_id": item['video_id'],
            "video_path": item['video_path']
        }
        results.append(merged_entry)
        print(f"[OK] Refined Spin ID {spin_id}: Identified {len(segments)} pose segments")

    # 4. Write to file
    with open(OUTPUT_JSONL, 'w', encoding='utf-8') as f:
        for entry in results:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    print(f"\n[SUCCESS] Second-level fine-grained division completed!")
    print(f"Results saved to: {OUTPUT_JSONL}")


if __name__ == "__main__":
    main()
